vim.api.nvim_create_user_command("MessagesWindow", function()
    vim.cmd("new")
    vim.cmd("setlocal buftype=nofile")
    vim.cmd("setlocal bufhidden=wipe")
    vim.cmd("setlocal noswapfile")
    vim.cmd("0put =execute('messages')")
end, {})
